---
# Supply ocp_host_name via --extra-vars
- name: Change oslab new worker VM MAC
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Change VM MAC
    vmware_guest_network:
      hostname: "{{ vsphere_address }}"
      username: "{{ vsphere_username }}"
      password: "{{ vsphere_password }}"
      validate_certs: no
      folder: "{{ ocp_vsphere_vm_folder }}"
      name: "{{ ocp_host_name }}"
      datacenter: "{{ vsphere_datacenter }}"
      esxi_hostname: "{{ esx2_host }}"
      networks:
      - label: "Network adapter 1"
        state: present
        manual_mac: "{{ item.mac }}"
    delegate_to: localhost
    register: deploy
    when: item.name == ocp_host_name
    with_items:
      - "{{ oslab_host_list }}"
