---
#
# var:cluster_admin_ip
# var:ontap_user
# var:lookup_password
# var:db_host_name
# var:oracle_sid
# var:backup_cmd
# var:db_vol_name
# var:arch_vol_name
# var:svm_name
# var:freeze_cmd
# var:thaw_cmd
# var:junction_root
# var:db_clone_name
# var:arch_clone_name
# var:number
# var:mount_clone
# var:clone_srv_ip
# var:dest_host_name
# var:dest_dbmount_point
# var:dest_archmount_point
# var:dest_mount_owner
# var:dest_mount_group
# var:dest_nfs_options
#
- hosts: "{{ dest_host_name if dest_host_name is defined else 'localhost' }}"
  gather_facts: no
  vars:
    dbmount: "{{ dest_dbmount_point if dest_dbmount_point is defined else '/mnt' }}"
    archmount: "{{ dest_archmount_point if dest_archmount_point is defined else '/mnt' }}"
    runumount: "{{ mount_clone if mount_clone is defined else 'false'|bool }}"
  tasks:
    - include_tasks: unmount_db_tasks.yaml
      when: runumount|bool == true
    - include_tasks: unmount_arch_tasks.yaml
      when: runumount|bool == true
- name: Delete Old Clone
  hosts: localhost
  vars:
    hostname: "{{ cluster_admin_ip }}"
    username: "{{ ontap_user if ontap_user is defined else 'admin' }}"
    password: "{{ ask_password if ask_password is defined else lookup('vars',lookup_password) if lookup_password is defined else ontap_password }}"
    dbvolume: "{{ db_vol_name if db_vol_name is defined else 'nfsvol' }}"
    archvolume: "{{ arch_vol_name if arch_vol_name is defined else 'nfsvol' }}"
    vserver: "{{ svm_name if svm_name is defined else 'svm0' }}"
    clone_num: "{{ number if number is defined else 1 }}"
    snapshot: "clone_snapshot_{{ '%02d'|format(clone_num|int) }}"
    dbclone: "{{ db_clone_name if db_clone_name is defined else dbvolume + '_' + '%02d'|format(clone_num|int) }}"
    archclone: "{{ arch_clone_name if arch_clone_name is defined else archvolume + '_' + '%02d'|format(clone_num|int) }}"
  tasks:
    - name: Unmount DB Clone
      ignore_errors: yes
      na_ontap_volume:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        https: true
        validate_certs: false
        junction_path: ''
        name: "{{ dbclone }}"
        vserver: "{{ vserver }}"
    - name: Offline DB Clone
      ignore_errors: yes
      na_ontap_volume:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        https: true
        validate_certs: false
        is_online: no
        name: "{{ dbclone }}"
        vserver: "{{ vserver }}"
    - name: Delete DB Clone
      ignore_errors: yes
      na_ontap_volume:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        https: true
        validate_certs: false
        state: absent
        name: "{{ dbclone }}"
        vserver: "{{ vserver }}"
    - name: Delete DB Snapshot
      na_ontap_snapshot:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        https: true
        validate_certs: false
        state: absent
        volume: "{{ dbvolume }}"
        vserver: "{{ vserver }}"
        snapshot: "{{ snapshot }}"
    - name: Unmount Arch Clone
      ignore_errors: yes
      na_ontap_volume:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        https: true
        validate_certs: false
        junction_path: ''
        name: "{{ archclone }}"
        vserver: "{{ vserver }}"
    - name: Offline Arch Clone
      ignore_errors: yes
      na_ontap_volume:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        https: true
        validate_certs: false
        is_online: no
        name: "{{ archclone }}"
        vserver: "{{ vserver }}"
    - name: Delete Arch Clone
      ignore_errors: yes
      na_ontap_volume:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        https: true
        validate_certs: false
        state: absent
        name: "{{ archclone }}"
        vserver: "{{ vserver }}"
    - name: Delete Arch Snapshot
      na_ontap_snapshot:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        https: true
        validate_certs: false
        state: absent
        volume: "{{ archvolume }}"
        vserver: "{{ vserver }}"
        snapshot: "{{ snapshot }}"
- hosts: "{{ db_host_name }}"
  gather_facts: no
  serial: 1
  vars:
    freezecmd: "{{ freeze_cmd if freeze_cmd is defined else '/home/oracle/oracle-scripts/db-hot-backup.sh -b -s ' + oracle_sid }}"
    thawcmd: "{{ freeze_cmd if freeze_cmd is defined else '/home/oracle/oracle-scripts/db-hot-backup.sh -e -s ' + oracle_sid }}"
  tasks:
    - name: Put database in hot backup mode
      block:
        - name: Start Backup Mode
          command: "{{ freezecmd }}"
      rescue:
        - name: Take databse out of backup mode
          command: "{{ thawcmd }}"
        - meta: end_play
- name: Create DB Clone
  hosts: localhost
  vars:
    hostname: "{{ cluster_admin_ip }}"
    username: "{{ ontap_user if ontap_user is defined else 'admin' }}"
    password: "{{ ask_password if ask_password is defined else lookup('vars',lookup_password) if lookup_password is defined else ontap_password }}"
    dbvolume: "{{ db_vol_name if db_vol_name is defined else 'nfsvol' }}"
    vserver: "{{ svm_name if svm_name is defined else 'svm0' }}"
    clone_num: "{{ number if number is defined else 1 }}"
    junction: "{{ junction_root + '/' if junction_root is defined else '/' }}"
    thawcmd: "{{ freeze_cmd if freeze_cmd is defined else '/home/oracle/oracle-scripts/db-hot-backup.sh -e -q -s ' + oracle_sid }}"
    snapshot: "clone_snapshot_{{ '%02d'|format(clone_num|int) }}"
    dbclone: "{{ db_clone_name if db_clone_name is defined else dbvolume + '_' + '%02d'|format(clone_num|int) }}"
    junction_db: "{{ junction_root + dbclone }}"
  tasks:
    - name: DB Volume Clone
      block:
        - name: Snapshot DB Volume
          na_ontap_snapshot:
            hostname: "{{ hostname }}"
            username: "{{ username }}"
            password: "{{ password }}"
            https: true
            validate_certs: false
            state: present
            volume: "{{ dbvolume }}" 
            vserver: "{{ vserver }}"
            snapshot: "{{ snapshot }}"
        - name: Clone DB Volume
          na_ontap_volume_clone:
            hostname: "{{ hostname }}"
            username: "{{ username }}"
            password: "{{ password }}"
            https: true
            validate_certs: false
            state: present
            parent_volume: "{{ dbvolume }}" 
            vserver: "{{ vserver }}"
            parent_snapshot: "{{ snapshot }}"
            junction_path: "{{ junction_db }}"
            volume: "{{ dbclone }}"
            space_reserve: none
      rescue:
        - name: Take databse out of backup mode
          delegate_to: "{{ db_host_name }}"
          command: "{{ thawcmd }}"
        - meta: end_play
- hosts: "{{ db_host_name }}"
  gather_facts: no
  serial: 1
  vars:
    thawcmd: "{{ freeze_cmd if freeze_cmd is defined else '/home/oracle/oracle-scripts/db-hot-backup.sh -e -s ' + oracle_sid }}"
  tasks:
    - name: Take database out of hot backup mode
      block:
        - name: End Backup Mode
          command: "{{ thawcmd }}"
      rescue:
        - meta: end_play
- name: Create Arch Clone
  hosts: localhost
  vars:
    hostname: "{{ cluster_admin_ip }}"
    username: "{{ ontap_user if ontap_user is defined else 'admin' }}"
    password: "{{ ask_password if ask_password is defined else lookup('vars',lookup_password) if lookup_password is defined else ontap_password }}"
    archvolume: "{{ arch_vol_name if arch_vol_name is defined else 'nfsvol' }}"
    vserver: "{{ svm_name if svm_name is defined else 'svm0' }}"
    clone_num: "{{ number if number is defined else 1 }}"
    junction: "{{ junction_root + '/' if junction_root is defined else '/' }}"
    snapshot: "clone_snapshot_{{ '%02d'|format(clone_num|int) }}"
    archclone: "{{ arch_clone_name if arch_clone_name is defined else archvolume + '_' + '%02d'|format(clone_num|int) }}"
    junction_arch: "{{ junction_root + archclone }}"
  tasks:
    - name: DB Volume Clone
      block:
        - name: Snapshot Arch Volume
          na_ontap_snapshot:
            hostname: "{{ hostname }}"
            username: "{{ username }}"
            password: "{{ password }}"
            https: true
            validate_certs: false
            state: present
            volume: "{{ archvolume }}" 
            vserver: "{{ vserver }}"
            snapshot: "{{ snapshot }}"
        - name: Clone Arch Volume
          na_ontap_volume_clone:
            hostname: "{{ hostname }}"
            username: "{{ username }}"
            password: "{{ password }}"
            https: true
            validate_certs: false
            state: present
            parent_volume: "{{ archvolume }}" 
            vserver: "{{ vserver }}"
            parent_snapshot: "{{ snapshot }}"
            junction_path: "{{ junction_arch }}"
            volume: "{{ archclone }}"
            space_reserve: none
- hosts: "{{ dest_host_name if dest_host_name is defined else 'localhost' }}"
  gather_facts: no
  vars:
    lif: "{{ clone_srv_ip if clone_srv_ip is defined else cluster_admin_ip }}"
    dbmount: "{{ dest_dbmount_point if dest_dbmount_point is defined else '/mnt' }}"
    archmount: "{{ dest_archmount_point if dest_archmount_point is defined else '/mnt' }}"
    owner: "{{ dest_mount_owner if dest_mount_owner is defined else 'root' }}"
    group: "{{ dest_mount_group if dest_mount_group is defined else 'root' }}"
    options: "{{ dest_nfs_options if dest_nfs_options is defined else 'rw,bg,hard,nointr,rsize=65536,wsize=65536,tcp,actimeo=0,vers=4,timeo=600' }}"
    clone_num: "{{ number if number is defined else 1 }}"
    dbvolumename: "{{ db_vol_name if db_vol_name is defined else 'nfsvol' }}"
    archvolumename: "{{ arch_vol_name if arch_vol_name is defined else 'nfsvol' }}"
    dbclone: "{{ db_clone_name if db_clone_name is defined else dbvolumename + '_' + '%02d'|format(clone_num|int) }}"
    archclone: "{{ arch_clone_name if arch_clone_name is defined else archvolumename + '_' + '%02d'|format(clone_num|int) }}"
    dbvolume: "{{ junction_root + '/' + dbclone if junction_root is defined else '/' + dbclone }}"
    archvolume: "{{ junction_root + '/' + archclone if junction_root is defined else '/' + archclone }}"
    runmount: "{{ mount_clone if mount_clone is defined else 'false'|bool }}"
  tasks:
    - include_tasks: mount_db_tasks.yaml
      when: runmount|bool == true
    - include_tasks: mount_arch_tasks.yaml
      when: runmount|bool == true
