---
# set vm_host_name with --extra-vars
- name: Start oslab VM
  hosts: localhost
  gather_facts: no
  vars:
    vm_host_name: worker
  tasks:
  - name: Start VM
    vmware_guest_powerstate:
      hostname: "{{ vsphere_address }}"
      username: "{{ vsphere_username }}"
      password: "{{ vsphere_password }}"
      validate_certs: no
      folder: "{{ ocp_vsphere_folder }}"
      name: "{{ vm_host_name }}"
      state: powered-on
    delegate_to: localhost
    register: deploy
