---
#
# var:kube_hosts
#
- name: Start k8s VMs
  hosts: localhost
  gather_facts: no
  vars:
    hostlist: "{{ kube_hosts if kube_hosts is defined else 'k8s' }}"
  tasks:
  - name: Set the state of kube host to power off
    vmware_guest_powerstate:
      hostname: "{{ vsphere_address }}"
      username: "{{ vsphere_username }}"
      password: "{{ vsphere_password }}"
      validate_certs: no
      folder: "{{ lab_vsphere_folder }}"
      name: "{{ item }}"
      state: powered-on
    delegate_to: localhost
    register: deploy
    with_items:
      - "{{ groups[hostlist] | list }}"
