---
#
# var:host_group
#
- name: Start SG VMs
  hosts: localhost
  gather_facts: no
  vars:
    hostlist: "{{ host_group if host_group is defined else 'storagegrid' }}"
  tasks:
  - name: Set the state of SG Nodes to poweron
    vmware_guest_powerstate:
      hostname: "{{ vsphere_address }}"
      username: "{{ vsphere_username }}"
      password: "{{ vsphere_password }}"
      validate_certs: no
      folder: "{{ lab_vsphere_folder }}"
      name: "{{ item }}"
      state: powered-on
    delegate_to: localhost
    register: deploy
    with_items:
      - "{{ groups[hostlist] | list }}"
