---
- name: Start labcluster VM
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Set the state of labcluster to poweron
    vmware_guest_powerstate:
      hostname: "{{ vsphere_address }}"
      username: "{{ vsphere_username }}"
      password: "{{ vsphere_password }}"
      validate_certs: no
      folder: "{{ lab_vsphere_folder }}"
      name: "{{ labcluster_node_name }}"
      state: powered-on
    delegate_to: localhost
    register: deploy
