---
- name: Start SDN VMs
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Start SDN VMs
    vmware_guest_powerstate:
      hostname: "{{ vsphere_address }}"
      username: "{{ vsphere_username }}"
      password: "{{ vsphere_password }}"
      validate_certs: no
      folder: "{{ lab_vsphere_folder }}"
      name: "{{ item }}"
      state: powered-on
    delegate_to: localhost
    register: deploy
    with_items:
      - "{{ network_hosts }}"
