---
- name: Start OpenShift Mirror Repository
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Set the state of ocp admin host to power on
    vmware_guest_powerstate:
      hostname: "{{ vsphere_address }}"
      username: "{{ vsphere_username }}"
      password: "{{ vsphere_password }}"
      validate_certs: no
      folder: "{{ ocp_vsphere_folder }}"
      name: "{{ item }}"
      state: powered-on
    delegate_to: localhost
    register: deploy
    with_items:
      - "{{ oslab_admin_host_list }}"
