---
- name: Stop oslab VMs
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Stop oslab VMs
    vmware_guest_powerstate:
      hostname: "{{ vsphere_address }}"
      username: "{{ vsphere_username }}"
      password: "{{ vsphere_password }}"
      validate_certs: no
      folder: "{{ ocp_vsphere_folder }}"
      name: "{{ item.name }}"
      state: powered-off
    delegate_to: localhost
    register: deploy
    with_items:
      - "{{ oslab_host_list }}"
