---
- name: Shutdown OCI
  hosts: ocidwh
  gather_facts: no
  tasks:
  - name: Shutdown DWH server
    win_shell: Stop-Computer -Force
  - name: Set the state of oci server to power off
    vmware_guest_powerstate:
      hostname: "{{ vsphere_address }}"
      username: "{{ vsphere_username }}"
      password: "{{ vsphere_password }}"
      validate_certs: no
      folder: "{{ lab_vsphere_folder }}"
      name: "{{ oci_server }}"
      state: shutdown-guest
    delegate_to: localhost
    register: deploy
