---
#
# var:mount_point
# var:host_group
#
- hosts: "{{ host_group if host_group is defined else 'production' }}"
  serial: 1
  vars:
    mount: "{{ mount_point if mount_point is defined else '/mnt' }}"
  tasks:
    - name: Remove nfs mount from host
      become: true
      become_user: root
      mount: 
        state: absent
        path: "{{ mount }}"
        fstype: nfs
