---
#
# var:mount_point
# var:host_group
#
- hosts: "{{ host_group if host_group is defined else 'production' }}"
  gather_facts: no
  serial: 1
  vars:
    mount: "{{ mount_point if mount_point is defined else '/mnt' }}"
  tasks:
    - include_tasks: unmount_nfs_tasks.yaml
